### ISSUE TITLE
Support asset change when updating transaction

### ISSUE THREAD

**Issue by fare** [SequentiaSEQ/SEQ-Core-Elements#43]
When changing the fee in a transaction (presumably with bumpfee / RBF — are there any other cases?), we currently only support a change in fee amount, not in fee asset. We want to support changing the fee asset. [We also only currently support bumping fees on unblinded transactions, but that's for another issue, this issue is only for the change in asset.]

Note that Bitcoin, and after it Elements and Sequentia, mandates a minimum bump in fee. In Sequentia, this minimum bump should be accounted in RFU / RFA (Reference Fee Unit / Reference Fee Atom, 1 RFU = 1e8 RFA), not in the fee asset used by the transaction (unclear if already done). Test cases should include cases where the amount changes up or down or stays the same, and the value is indeed bumped enough or isn't. Test cases should also include cases where the asset (and amount?) stay the same, but the value is bumped (or isn't) because the exchange rate changed. Also note that among those cases, if the asset is unchanged and the amount doesn't increase, the value cannot increase past the positive bump and so the new transaction should be rejected.

**Comment by Mixa84** [comment]
Already impelmented in bumpfee in #30
